### ISSUE TITLE
How to improve query speed in Grafana?

### ISSUE THREAD

**Issue by linux-time** [VictoriaMetrics/victorialogs-datasource#103]
I created a dashboard in Grafana to analyze API response times, grouping them by 1-100ms, 101-300ms, 301-1s, and over 1s. When the time range is within 1 hour, the chart is very fast, but when the time range is longer, it becomes very slow and may even time out.

Is there something wrong with my query? Here is my query:

_stream:{domain=~ ".*"} | fields @timestamp, request_time_v2 | request_time_v2:>=1 and request_time_v2:<=100 | by (@timestamp:$__interval) count()

I know that victorialogs will improve query speed on the second query. Is there a way to make victorialogs pre-query some data?

Thanks！

**Comment by tiny-pangolin** [comment]
Yes this can be done using recording rules. In version 1.106 vmalert gained support for evaluating rules from Victorialogs and storing the results in Victoriametrics or another remotewrite target

https://docs.victoriametrics.com/victorialogs/vmalert/

**Comment by linux-time** [comment]
> Yes this can be done using recording rules. In version 1.106 vmalert gained support for evaluating rules from Victorialogs and storing the results in Victoriametrics or another remotewrite target
> 
> https://docs.victoriametrics.com/victorialogs/vmalert/

Thank you for your answer, I will try it first and let me know if there are any problems.

**Comment by tiny-pangolin** [comment]
Closing issue please reopen if recording rules don't solve your problem
