### ISSUE TITLE
Support $__range variable in queries

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/victorialogs-datasource#112]
Add support for the $__range variable in queries. This would enable queries like `_time: $__range | stats by(host) count()` to retrieve stats for the time range selected in the Grafana time picker.

_Originally posted by @hagen1778 in https://github.com/VictoriaMetrics/victorialogs-datasource/issues/61#issuecomment-2487919910_

**Comment by dmitryk-dk** [comment]
Hi @Loori-R ! The issue was fixed in the new [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.9.0). Close as implemented. Feel free to reopen if you find any problems.
