### ISSUE TITLE
Add support for legend template

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/victorialogs-datasource#114]
Allow customization of the legend template to choose which labels from the result should appear in the legend. Currently, there is no way to control the legend display.

<img width="344" alt="image" src="https://github.com/user-attachments/assets/c0c36484-5eb8-491b-b652-46396b488f3c">

_Originally posted by @hagen1778 in https://github.com/VictoriaMetrics/victorialogs-datasource/issues/61#issuecomment-2487919910_

**Comment by dmitryk-dk** [comment]
Hi @Loori-R ! The feature was added in the new plugin [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.10.0). Close this issue as resolved. Feel free to reopen the issue if you find any problems.
