### ISSUE TITLE
Time range resets to 24 hours on variables refresh in Grafana 11.3 when using query variables

### ISSUE THREAD

**Issue by p5i** [VictoriaMetrics/victorialogs-datasource#118]
After updating Grafana to v11.3.0 or v11.3.1 time range resets to 24 hours when variables are refreshed.
To reproduce you can add variable of type 'query', make it refresh on time range change, than build the time series graph.
Try to change time range to less then 24 hours and it will remain 24 hours.

![photo](https://github.com/user-attachments/assets/859a5d9e-17cf-4d03-ae01-c0e0d204a515)

I tried the datasource versions v0.8.0 and v0.7.0

**Comment by koriit-kontakt** [comment]
Hi, we are having the same issue. It started happening after upgrading to Grafana v11.3.0 from v11.2.2. We tested it with datasource versions v0.6.1 and v0.9.0.

@p5i the workaround of not having variables refresh on time range change is also working in our case, thanks a lot!

**Comment by dmitryk-dk** [comment]
Hi @p5i , @koriit-kontakt ! I Suppose this issue is related to this [issue](https://github.com/grafana/grafana/issues/95443)

**Comment by p5i** [comment]
Hi @dmitryk-dk 
Thanks for the answer.
That issue may be related, but not exactly the same, according to the description.
I don't have InfluxDB to check if there is similar problem.
I use also Graphite and Loki datasources and there is no such issues.

My problem is that time range of the query differs from time range specified on the dashboard. For example I set 1 munute range on the dashboard, but in the query I see 24 hours (23:59:59 exactly) range.

On the dashboard:
![2024-12-05 12-12-29](https://github.com/user-attachments/assets/e1068c18-431c-4356-ba41-aa823d4f88d2)

In the Query Inspector:
![2024-12-05 12-12-55](https://github.com/user-attachments/assets/a58a15e3-97df-402f-a96b-bf1dd790f63d)

The query to VL from the network dump:
```POST /select/logsql/stats_query_range?end=1731963599&query=%2A%7C+stats+count%28%29&start=1731877200&step=1m0s HTTP/1.1 ```

```
date -u -d @1731877200
Sun Nov 17 21:00:00 UTC 2024

date -u -d @1731963599
Mon Nov 18 20:59:59 UTC 2024
```



Reproduced with Grafana v11.3.2 and victorialogs-datasource v0.10.0

**Comment by hagen1778** [comment]
Weirdly, I can reproduce the issue at [playground](https://play-grafana.victoriametrics.com/d/be5zidev72m80f/k8s-logs-demo?orgId=1&from=now-24h&to=now&timezone=browser&var-ds=P566C6523BE02F42C&var-namespace=$__all&var-pod=$__all&var-container=$__all&var-filter=%2A&var-limit=500) with latest Grafana version. But can't do it in our internal snadbox that runs v11.2.1

**Comment by p5i** [comment]
I built the datasource plugin with the https://github.com/VictoriaMetrics/victorialogs-datasource/pull/137 fix. It doesn't seam to fix time range reset.

**Comment by dmitryk-dk** [comment]
> I built the datasource plugin with the #137 fix. It doesn't seam to fix time range reset.

@Loori-R could you take a look, please?

**Comment by p5i** [comment]
@Loori-R Thanks. Checked in Chromium browser and in private mode in Firefox. Both ways work fine. It is some Firefox caching problem.

**Comment by dmitryk-dk** [comment]
Hi @p5i ! The issue was fixed in the new [release](https://github.com/VictoriaMetrics/victorialogs-datasource/tree/v0.11.0). Please check it. If you find any problems feel free to reopen the issue.

**Comment by koriit-kontakt** [comment]
v0.11.0 fixed this issue for us. Thanks a lot!
