### ISSUE TITLE
How do older versions of Grafana work

### ISSUE THREAD

**Issue by whc9527** [VictoriaMetrics/victorialogs-datasource#123]
victorialogs-datasource of v0.8.0 was installed in Grafana v7.5.17. When I added a new datasource to the Grafana console, I got an error. Is there a workaround without upgrading Grafana?
![image](https://github.com/user-attachments/assets/5d1fc068-5014-4c63-91a7-b6dca7d6945d)

**Comment by Loori-R** [comment]
Hi @whc9527,

victorialogs-datasource plugin supports Grafana version `10.0.3` and above. At this time, we do not plan to provide support for earlier versions of Grafana.

Unfortunately, I believe it is unlikely that this issue can be resolved without upgrading Grafana.

**Comment by whc9527** [comment]
@Loori-R thanks Loori-R, i get it
