### ISSUE TITLE
Add Options > Legend + Type + Step in Grafana visualizations

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/victorialogs-datasource#124]
In Grafana, when using Loki data source I'm able to specify fields to be displayed in the Legend:
![image](https://github.com/user-attachments/assets/1aacc6b5-4106-4018-a4f4-ed7cb2e4baa1)
![image](https://github.com/user-attachments/assets/2435e7f5-60a6-48d8-b2ed-a2b5e9c63c17)
Can we please enable the same feature for the VictoriaLogs data source?
Currently, there is no Options at all:
![image](https://github.com/user-attachments/assets/3fd414d7-2aeb-4704-831c-ab6da5590f5f)

**Comment by Loori-R** [comment]
This issue duplicates the following existing issues:  

- **Options > Type**: Refer to [#111](https://github.com/your-repo/issues/111)  
- **Options > Legend**: Refer to [#114](https://github.com/your-repo/issues/114)

**Comment by arseny-zinchenko** [comment]
Thanks, @Loori-R 
Just in the links you added is `your-repo` instead of `VictoriaMetrics/victorialogs-datasource`
[111](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/111)
[114](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/114)
