### ISSUE TITLE
Wrong $__interval_ms substitution in queries

### ISSUE THREAD

**Issue by koriit-kontakt** [VictoriaMetrics/victorialogs-datasource#125]
Hi, thank you for VictoriaLogs and datasource for Grafana. You made querying logs great again for us.

## Problem
The `$__interval_ms` variable gets substituted with nanos instead of millis as one would expect. The same happens in dashboards and Explore.

## Workaround
To get per second rate, instead of using `| math count / ($__interval_ms/1000) as count` as I was used to so far, I was able to make it work with this: `| math count / ($__interval/1s) as count`

## Version
Grafana v11.2.2 (dbf571744d)
VictoriaLogs installed from victoria-logs-single helm chart in version 0.7.1
victorialogs-datasource v0.6.1

## Evidence
Note: I have some transformations but they don't affect the result.

Problematic result:
![image](https://github.com/user-attachments/assets/3e27f13b-ea8e-43f1-a07f-6c619b9c348a)

The correct result with the workaround:
![image](https://github.com/user-attachments/assets/5187d756-42f8-4ed4-943a-1f1eb520d9ae)

Replacing result with `$__interval_ms` as-is:
![image](https://github.com/user-attachments/assets/62394579-cb75-43c0-ad65-50d16eba679c)

Query inspector for the above query:
```json
"queries": [
        {
          "datasource": {
            "type": "victorialogs-datasource",
            "uid": "xxxx"
          },
          "refId": "A",
          "editorMode": "code",
          "expr": "namespace:\"prod-0\" job:\"prod-0/dm-api\" \"PerformanceFilter\" \"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\"  | unpack_json | stats by (_time:$__interval,request.api,response.status) count() count | math $__interval_ms   as count",
          "queryType": "range",
          "maxLines": 1000,
          "legendFormat": "",
          "datasourceId": 5,
          "intervalMs": 60000,
          "maxDataPoints": 1978
        }
      ],
```

**Comment by dmitryk-dk** [comment]
Hi @koriit-kontakt ! I have checked two versions of the Grafana (v10.4.0 and v11.3.0) and got this results on both of the Grafana versions

This is log from the grafana
Grafana v10.4.0
```
INFO [12-02|22:20:25] INTERVAL                                 logger=plugin.victorialogs-datasource interval=2000.000
INFO [12-02|22:20:25] EXPR                                     logger=plugin.victorialogs-datasource expr=*
INFO [12-02|22:20:25] Query                                    logger=plugin.victorialogs-datasource interval=2000.000 query=* timeRange="map[From:2024-12-02T21:20:25.177+01:00 To:2024-12-02T22:20:25.177+01:00]"
INFO [12-02|22:20:36] INTERVAL                                 logger=plugin.victorialogs-datasource interval=2000.000
INFO [12-02|22:20:36] EXPR                                     logger=plugin.victorialogs-datasource expr="* | stats by (_time:2s) count() count | math 2000 as time"
INFO [12-02|22:20:36] Query                                    logger=plugin.victorialogs-datasource query="* | stats by (_time:2s) count() count | math 2000 as time" timeRange="map[From:2024-12-02T21:20:36.633+01:00 To:2024-12-02T22:20:36.633+01:00]" interval=2000.000
INFO [12-02|22:20:50] INTERVAL                                 logger=plugin.victorialogs-datasource interval=60000.000
INFO [12-02|22:20:50] EXPR                                     logger=plugin.victorialogs-datasource expr="* | stats by (_time:1m) count() count | math 60000 as time"
INFO [12-02|22:20:50] Query                                    logger=plugin.victorialogs-datasource interval=60000.000 query="* | stats by (_time:1m) count() count | math 60000 as time" timeRange="map[From:2024-12-01T22:20:50.433+01:00 To:2024-12-02T22:20:50.433+01:00]"
```

Grafana v11.3.0
```
INFO [12-02|22:24:28] INTERVAL                                 logger=plugin.victorialogs-datasource interval=60000.000
INFO [12-02|22:24:28] EXPR                                     logger=plugin.victorialogs-datasource expr="* | stats by (_time:1m) count() count | math 60000 as time"
INFO [12-02|22:24:28] Query                                    logger=plugin.victorialogs-datasource interval=60000.000 query="* | stats by (_time:1m) count() count | math 60000 as time" timeRange="map[From:2024-12-01T22:24:28.232+01:00 To:2024-12-02T22:24:28.232+01:00]"
```

Here are the responses
Grafana v10.4.0
<img width="1792" alt="Screenshot 2024-12-02 at 22 23 00" src="https://github.com/user-attachments/assets/0b599531-9aef-4e98-be70-f3960785c335">

Grafana v11.3.0
<img width="1799" alt="Screenshot 2024-12-02 at 22 25 19" src="https://github.com/user-attachments/assets/5eb118ee-433e-405a-bb89-7c7adbf67abc">

What version of the Grafana do you use?
What datasource version do you use?

**Comment by koriit-kontakt** [comment]
Hi, thanks for checking. 

Grafana v11.2.2 (dbf571744d)
VictoriaLogs installed from victoria-logs-single helm chart in version 0.7.1
victorialogs-datasource v0.6.1

For comparison here is the result of your query in my setup:
![image](https://github.com/user-attachments/assets/8645b1b1-7ade-49c9-b476-4cb4ce0abc8e)

**Comment by koriit-kontakt** [comment]
Isn't #121 related to a different variable?

I will ask my guys to update to the latest datasource version and see if the issue persists.

**Comment by dmitryk-dk** [comment]
> Isn't #121 related to a different variable?
> 
> I will ask my guys to update to the latest datasource version and see if the issue persists.

I added both in the mentioned PR, $__range and $__interval_ms
https://github.com/VictoriaMetrics/victorialogs-datasource/pull/121/files#diff-81ddbadfb415ccbb9c7af84f11668d1aa5e53c34025bf86d4702f16b4e42f045R194

**Comment by koriit-kontakt** [comment]
Oh ok, then awaiting new release. Thanks.

**Comment by dmitryk-dk** [comment]
> Oh ok, then awaiting new release. Thanks.

Could you, please, upgrade your data source version to the newest release [version](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.9.0)?

**Comment by koriit-kontakt** [comment]
Yes. That was fast. :D I will upgrade and let you know of the result.

**Comment by koriit-kontakt** [comment]
Thanks! In 0.9.0 this issue does not occur anymore:
![image](https://github.com/user-attachments/assets/69339b11-e79b-4384-b639-74b43c0870f5)

Seems there were other changes between 0.6.1 and 0.9.0, that broke some of my dashboards. But that's actually a good change, becaue what broke are my workarounds for unexpected behaviour of the datasource. Basically they are not needed anymore.
