### ISSUE TITLE
Different behaviour when querying in VMUI vs Grafana

### ISSUE THREAD

**Issue by tommysitehost** [VictoriaMetrics/victorialogs-datasource#134]
Hey guys, here is something i found

Querying the same query but grafana returns an error (only min and max stats, avg, mean stats are fine)
![image](https://github.com/user-attachments/assets/b7b5a2d7-5107-4229-bae0-357c22c6faef)

VMUI returned multiple results
![vmui](https://github.com/user-attachments/assets/fe7c11dc-9625-45b0-8f32-2d3e409b0771)

However, avg stats is ok but only returned 1 result
![image](https://github.com/user-attachments/assets/6d919883-a859-4aa7-ad77-c875dbd93c49)

VMUI returned multiple results 
![vmui](https://github.com/user-attachments/assets/82c87e79-d68e-4bc4-a778-579421cebe33)

I would expect the same behaviour when I query from VMUI vs Grafana. Is this the case?

**Comment by tommysitehost** [comment]
Hi @Loori-R, thanks for your quick response. Would the Grafana Datasource support ` /select/logsql/hits` endpoint in the future?

**Comment by Loori-R** [comment]
> Hi @Loori-R, thanks for your quick response. Would the Grafana Datasource support ` /select/logsql/hits` endpoint in the future?

Yes, support for the `/select/logsql/hits` endpoint is planned. You can follow the progress here: [#15](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/15).

**Comment by dmitryk-dk** [comment]
Hi @tommysitehost ! 
I checked your request and the plugin works well. Because stats and stats range [API](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) works with numbers. And your request will return something like `{"max(body.hostname)":"we.xn--yfro4i67o"}`. 

You should modify your query to get the correct results from from the VictoriaLogs

**Comment by tommysitehost** [comment]
hey @dmitryk-dk,

I just wanna point out that min and max stats do not work on the same dataset, while the avg, mean stats work.
![image](https://github.com/user-attachments/assets/afe9f3f5-9b93-42d1-8624-5e1ee884495f)

**Comment by dmitryk-dk** [comment]
> hey @dmitryk-dk,
> 
> I just wanna point out that min and max stats do not work on the same dataset, while the avg, mean stats work. ![image](https://private-user-images.githubusercontent.com/61849757/393640694-afe9f3f5-9b93-42d1-8624-5e1ee884495f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzU5NjIsIm5iZiI6MTczMzczNTY2MiwicGF0aCI6Ii82MTg0OTc1Ny8zOTM2NDA2OTQtYWZlOWYzZjUtOWI5My00MmQxLTg2MjQtNWUxZWU4ODQ0OTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZTQyYzZlNTljYTY1ZjMzZjkwNTE4NWM0Y2JlZjgwMDEzNGFmYzc3NTFkMWIzNWMzOTJhMmZmMWQyODdlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r30EOcHgjygz3MnK5p41UlsStr_FpMJmJA0HAy6lz6U)

Can you create an issue in the VictoriaMetrics repository and describe this issue. Because the plugin just transfer data from VictoriaLogs to the Grafana.

**Comment by Loori-R** [comment]
@tommysitehost, FYi: victorialogs-datasource supports `/select/logsql/hits` starting from [v0.11.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases).
