### ISSUE TITLE
ad-hoc filtering is applied incorrectly

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/victorialogs-datasource#135]
Use `TimeSeries` and `Logs` panels together on the same dashboard. Display some logs in `Logs` panel and try filtering by one of the fields:
<img width="901" alt="image" src="https://github.com/user-attachments/assets/e49814c6-4067-49ce-8118-df34f6f14fde">

Filter is applied incorrectly and breaks all other panels on the dashboard:
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/acfb4dc1-544b-49e4-8c16-094ead20009f">

The original query used for one of the panels:
```
kubernetes.pod_namespace:~"$namespace" kubernetes.pod_name:~"$pod" kubernetes.container_name:~"$container" 
| stats by (kubernetes.pod_name,kubernetes.container_name) count() logs_total 
| filter logs_total: > 10 
| math(logs_total/$_interval)
```

The resulting query sent by Grafana after filtering by field value in the table:
```
kubernetes.pod_namespace:~"argocd" kubernetes.pod_name:~".*" kubernetes.container_name:~".*" 000000000000000006fe3869127251e6c8c8bbee1a18bfbc _stream_id:"=" | stats by (kubernetes.pod_name,kubernetes.container_name) count() logs_total | filter logs_total: > 10 | math(logs_total/$_interval)
```

The part `000000000000000006fe3869127251e6c8c8bbee1a18bfbc _stream_id:"=" ` is syntaxtically incorrect for LogsQL.

**Comment by dmitryk-dk** [comment]
Hi! The issue was fixed in the new [release](https://github.com/VictoriaMetrics/victorialogs-datasource/tree/v0.11.0). Please check it. If you find any problems feel free to reopen the issue
