### ISSUE TITLE
Range request with millisecond step is rounded to whole seconds

### ISSUE THREAD

**Issue by p5i** [VictoriaMetrics/victorialogs-datasource#147]
Hi!

When building the time series request with "range" type and 10ms step, the returned data is rounded to seconds. This leads to bar-like graph and overlay of points.
Here the top graph is built with the "raw" query type and converted to time series with Grafana's tranformations. The bottom one is of "range" type. The queries are similar `* | stats by(_time:10ms) count()` and `* | stats count()`.
![2024-12-10 11-56-10](https://github.com/user-attachments/assets/fe312741-db2b-4829-ba64-6e7388720fa5)

And here everything is on one screen. Query, step, graph and response.
![2024-12-10 11-46-22](https://github.com/user-attachments/assets/af136d24-1ff8-4ace-86ac-8405ab43e614)

The query is correctly converted to VL query with step 10ms 
`POST /select/logsql/stats_query_range?end=1733187154&query=%2A+%7C+stats+count%28%29&start=1733187134&step=10ms HTTP/1.1`
The response from VL contains timestamps with millisecond precision.
```
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "count(*)"
        },
        "values": [
          [
            1733187134.04,
            "4"
          ],
          [
            1733187134.16,
            "4"
          ],
          [
            1733187134.1699998,
            "4"
          ],
          [
            1733187134.29,
            "4"
          ],
          [
            1733187134.7,
            "4"
          ],
          [
            1733187134.77,
            "4"
          ],
          [
            1733187134.7900002,
            "40"
          ],
          [
            1733187134.8,
            "8"
...
```

But then the timestamps are rounded to seconds by datastore plugin or by Grafana.

**Comment by dmitryk-dk** [comment]
Hi @p5i ! The issue was fixed in the latest [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.12.0). Please check it. If you find any problem with it, feel free to reopen the issue

**Comment by p5i** [comment]
@dmitryk-dk Thank you very much. Works great in v0.12.0
