### ISSUE TITLE
v0.11 fails to load in Grafana

### ISSUE THREAD

**Issue by dhess** [VictoriaMetrics/victorialogs-datasource#149]
Hi, thanks for this project!

We use this datasource with the Grafana Operator (which installs Grafana v10.4.14), and everything has been working great until we upgraded to `v0.11` today. Now when we attempt to select the VictoriaLogs datasource on the Explore page, we get the following error in the UI:

```
VictoriaLogs plugin failed
TypeError: undefined is not an object (evaluating 'Object.keys(h.scopeFilterOperatorMap)')
```

and the selection returns to the default (VictoriaMetrics).

There aren't any obvious messages in the logs, and I can confirm that VictoriaLogs `0.11.0` appears in the Grafana plugins page.

**Comment by dmitryk-dk** [comment]
Close issue as solved
