### ISSUE TITLE
Support vlogs new features: pipes and stats (pipe confuses the parser)

### ISSUE THREAD

**Issue by grinapo** [VictoriaMetrics/victorialogs-datasource#22]
Recent victorialogs supports marvelous features, namely **pipes**. However it breaks the logic in datasource:

`cannot parse query [_time:[2024-05-16T11:56:06.733Z, 2024-05-16T17:56:06.733Z] AND (severity:warning | stats count() logs)]: unexpected token "|" instead of ')'; context: [ 2024-05-16T17:56:06.733Z] AND (severity:warning |]`

The problem is that time gets inserted as 
`_time:XX   AND ( <query_string> )` 
and pipe shall be at the end, outside of the parens. The easiest is probably simply put everything after and including the first pipe outside the parentheses.

**Comment by hagen1778** [comment]
@Loori-R shall we remove support of `_time` filter in favour of Grafana's time picker?

**Comment by Loori-R** [comment]
start and end query args The `_time` value is inserted from Grafana's time picker. We need to replace `_time` with `start` and `end` query args, similar to what was done in [PR #6296](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6296).

**Comment by Loori-R** [comment]
@grinapo, As a temporary solution, you can manually specify `_time` in the expression. In this case, it will not be set automatically, allowing you to use **pipes** until we fix this issue.

**Comment by dmitryk-dk** [comment]
Hi @grinapo ! The latest [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.2.2) should fix your issue. Could you check it?

**Comment by grinapo** [comment]
@dmitryk-dk as far as I am able to test it works flawlessly. Thank you!

**Comment by dmitryk-dk** [comment]
Close as solved. Thank you!
