### ISSUE TITLE
Publish logs readme to docs/VictoriaLogs folder in Main Issue

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/victorialogs-datasource#33]
- Please add automation and publish the docs to site
- Update VictoriaLogs docs and mention datasource there

**Comment by hagen1778** [comment]
@tenmozes I suppose it is related to https://github.com/VictoriaMetrics/victorialogs-datasource/pull/39 ?

**Comment by zekker6** [comment]
@hagen1778 Yes, exactly. We can close this one as it was alredy merged

**Comment by hagen1778** [comment]
Docs are now automatically synced to https://docs.victoriametrics.com/victorialogs/victorialogs-datasource/index.html
See https://github.com/VictoriaMetrics/victorialogs-datasource/pull/39 for details
