### ISSUE TITLE
Specific plugin error message is not propagated to the client

### ISSUE THREAD

**Issue by grinapo** [VictoriaMetrics/victorialogs-datasource#34]
While testing #22 I created some not quite valid queries it seems, which is fine (or at least I believe that at this point :-)).
However all I got was a generic "`500 An error occurred within the plugin`".

Checking the grafana logs I see the real message there:

`logger=context userId=2 orgId=1 uname=grin t=2024-06-26T15:46:57.572889164+02:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to query data: Failed to query data: rpc error: code = Unknown
 desc = frame has different field lengths, field 0 is len 360 but field 1 is len 0" remote_addr=xyz traceID=`

I am not sure that it's possible to forward the specific message to the client (most plugins do that), but if it is, it would be extremely useful.

ps: "`severity:info | stats by (_time:1m) count() logs`"

**Comment by dmitryk-dk** [comment]
Hi @grinapo ! Could you please try to upgrade the plugin to the latest release and be sure that the backend part or Grafana was restarted.? Why I am asking - this issue was fixed in the newest release, and I have checked your query on my local and our prod end, and it works well; just shows me no data message. But do not return any error.

**Comment by dmitryk-dk** [comment]
@grinapo , @crocchietta ! Thank you for the provided information. I found the reason and prepared the fix. Need to test it a little bit

**Comment by crocchietta** [comment]
When is the next release with this fix planned?

**Comment by dmitryk-dk** [comment]
> When is the next release with this fix planned?

Maybe i will do it today

**Comment by crocchietta** [comment]
Thanks.

**Comment by crocchietta** [comment]
I just tried the fix and there are no more errors.

On the other hand, I can't use the result of the query with time series visualization. I get a "Data is missing a number field".
Here is the result of the query:
```
2024-06-28 09:50:00.000	{"logs":"2"}
2024-06-28 07:32:00.000	{"logs":"1"}
2024-06-28 07:35:00.000	{"logs":"2"}
2024-06-28 08:04:00.000	{"logs":"1"}
2024-06-28 08:35:00.000	{"logs":"2"}
```
But maybe it's not possible to do that yet?

**Comment by dmitryk-dk** [comment]
Hi @grinapo , @crocchietta ! Here is the [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.2.3). Could you check it, please? If it works correctly, can you close the issue?

**Comment by crocchietta** [comment]
It's ok for me.

@dmitryk-dk : Is it possible to use the result of a query for serial times (as with Loki) or is it only planned for later?

**Comment by grinapo** [comment]
@dmitryk-dk this issue seems to have been taken over by the evil _stream field id problem_ (which indeed have been fixed), but the original issue was more generic: the plugin shall hand over to grafana the specific error message, and not just "got unexpected response status code: 400".

(to test: `foo | stats evilverb (_time:1m) count()` - should tell me where and what the error was.)

**Comment by dmitryk-dk** [comment]
Hi @grinapo , @crocchietta ! We can close this issue related to the described problem. And you can open new ones with improvements to the errors. If this works for you, I would appreciate a new issue from your side, and I'll close this one.

Thank you:)

**Comment by crocchietta** [comment]
it's ok for me.

**Comment by dmitryk-dk** [comment]
Close as solved. Open new issue related error improvements, please. Thank you!
