### ISSUE TITLE
Variable values fetch from query

### ISSUE THREAD

**Issue by Neko-Follower** [VictoriaMetrics/victorialogs-datasource#40]
Hi!
Thank you for the datasource plugin.

I wanted to get the variable values ​​from the query rather than defining them manually.
<img width="553" alt="Снимок экрана 2024-07-04 в 16 18 51" src="https://github.com/VictoriaMetrics/victorialogs-datasource/assets/83747975/1b8bcbb4-f7d1-494b-a57b-1094590ea03b">

**Comment by hagen1778** [comment]
@Loori-R @dmitryk-dk would you mind taking a look?

**Comment by pgassmann** [comment]
I would like to build a logs dashboard like this using victorialogs:

![grafik](https://github.com/VictoriaMetrics/victorialogs-datasource/assets/460192/44d185ed-fbcd-4382-a0fa-5f76a1615839)
![grafik](https://github.com/VictoriaMetrics/victorialogs-datasource/assets/460192/6b245102-1e23-4874-85c0-731fa430e6d9)

The query for loki looks like this:
```
{host=~"$host",category="dockerlogs",compose_project=~"$project",compose_service=~"$service"} $filter |~ "$search" 
| line_format "{{.compose_project }}/{{.compose_service }}\t| {{ __line__ }}"
```

For this, the grafana plugin would need to support querying field_values. The api is implemented: 
https://docs.victoriametrics.com/victorialogs/querying/#querying-stream-field-values

**Comment by ccgovuk** [comment]
Dynamic variables allow some really useful dashboarding, looking forward to being able to do this with victorialogs.

**Comment by dginhoux** [comment]
Hi, 

I agree, allow creating vars is very usefull. It can help to focus on specific point.
It can be use to create clean dashboards with both vmlogs and vmetrics content.

**Comment by hagen1778** [comment]
@Loori-R is https://github.com/VictoriaMetrics/victorialogs-datasource/pull/58 enough for supporting variables in the plugin?

**Comment by Neko-Follower** [comment]
Hi! Thank you for feature. I tried this out and found some bugs.

Multi-value seems doesn't work. I have query: 
`consumer: $consumer`
Choose 2 options and get nothing. From google devtools in network i see following query:
`consumer: <null>|admin`
I think it should have looked like this:
`consumer: ("<null>" OR "admin")`

Query works badly with values with special characters. I have query:
`proxy_list: $proxy_list`
From google devtools in network i see following query:
`proxy_list: api_name:clientid-persons-v1;v1\\.14\\.1`
I think it should have looked like this:
`proxy_list: "api_name:clientid-persons-v1;v1.14.1"`

I think need to add quotes and work through the moment with multi-value

**Comment by Loori-R** [comment]
Hi @Neko-Follower! Thank you for the feedback. 
I created a separate [issue #65](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/65).

**Comment by Loori-R** [comment]
The functionality for fetching variable values is supported in `victorialogs-datasource` starting from version [v0.3.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.3.0).
