### ISSUE TITLE
Sort enties by time automaticaly 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/victorialogs-datasource#47]
The same as in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6669

**Comment by valyala** [comment]
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6669#issuecomment-2242152687

**Comment by hagen1778** [comment]
So as I understand from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6669#issuecomment-2242152687 no sorting needs to be added to the plugin @Loori-R ?

**Comment by Loori-R** [comment]
I think we can keep the sorting that the server returns. The table view allows changing the sorting.
