### ISSUE TITLE
The license description at the bottom of the project landing page says AGPL, but the link it goes to is Apache and it seems it should be Apache?

### ISSUE THREAD

**Issue by chrisfw** [VictoriaMetrics/victorialogs-datasource#49]
The license description at the bottom of the project landing page says AGPL, but the link it goes to is Apache and it seems it should be Apache?

**Comment by tiny-pangolin** [comment]
I believe this should be apache 2.0 [here](https://github.com/VictoriaMetrics/victorialogs-datasource/pull/52) is the MR which should fix the issue

**Comment by tiny-pangolin** [comment]
mr has been merged thanks for bringing this to our attention
