### ISSUE TITLE
Dynamic variables using label values got: "Error updating options: this is undefined"

### ISSUE THREAD

**Issue by 2333** [VictoriaMetrics/victorialogs-datasource#64]
Hi, thanks for updating datasource with dynamic variables, I'm really looking forward to use it on my dashboard. So when I updated my plugin when I see it's released.
But when I'm trying to use it, I've got an error: "Error updating options: this is undefined", any hinds of this?
My grafana version is v10.1.2 and victorialogs-datasource is v0.3.0.
![image](https://github.com/user-attachments/assets/22904762-faf1-4415-bfe7-120a6bd16a9f)
thank you.
BR

**Comment by Loori-R** [comment]
Hi @2333, could you please share the error from the DevTools console?

**Comment by 2333** [comment]
> Hi @2333, could you please share the error from the DevTools console?

Hi @Loori-R, here's console output, plz let me know if you need more information.

![image](https://github.com/user-attachments/assets/6ad3153c-96dd-429f-960d-0c8ee365788e)

**Comment by dmitryk-dk** [comment]
Hi @2333 ! The issue was fixed in the [v0.4.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.4.0) release. Fill free to reopen the issue if you find some problems
