### ISSUE TITLE
Query filter does not work

### ISSUE THREAD

**Issue by Neko-Follower** [VictoriaMetrics/victorialogs-datasource#72]
Hi. I want to use query filter, but it doesn't seem to work
![image](https://github.com/user-attachments/assets/6563c1c6-d1ee-459b-84a2-60ea2c2aca89)

**Comment by dmitryk-dk** [comment]
Hi @Neko-Follower ! I have checked this question on my local, and it works. See examples below
1. With all values
<img width="1799" alt="Screenshot 2024-09-06 at 10 48 46" src="https://github.com/user-attachments/assets/d6e894db-2917-4921-99de-045806700032">

2. With only stdout value
<img width="1799" alt="Screenshot 2024-09-06 at 10 49 50" src="https://github.com/user-attachments/assets/fff49fc9-0559-454e-8986-c215fc22c5ab">

Could you please share the version of the grafana?

**Comment by Neko-Follower** [comment]
I removed the space. It didn't work
![Снимок экрана 2024-09-06 в 15 41 06](https://github.com/user-attachments/assets/c6a1619e-cde5-4103-9d37-59ff2676633a)

My Grafana version - 11.1.4
I saw in #71 issue you use Grafana version 9.5.21. How you use it if datasource requires version >= 10.0.3?
![Снимок экрана 2024-09-06 в 15 46 03](https://github.com/user-attachments/assets/ef5d3c6e-8432-4cf6-bccb-0295ebe68871)

I'll try to downgrade Grafana to 10 and test.

**Comment by dmitryk-dk** [comment]
Checked with 11.1.4. It takes some time to return a response, and maybe you have a proxy in between the Grafana and Victorialogs that may stop the request for some time. It is just my assumption because you have the error like 504 gateway timeout. But can you check that you do not have any proxy
<img width="1800" alt="Screenshot 2024-09-06 at 13 03 31" src="https://github.com/user-attachments/assets/9ecacc75-998c-4b86-9893-9e24f81f5070">

**Comment by Neko-Follower** [comment]
You are right. It is error 504 gateway timeout. I looked and there is no proxy between grafana and victorialogs.
Also I looked at victorialogs logs:
```
{"ts":"2024-09-06T11:09:12.526Z","level":"warn","caller":"VictoriaMetrics/app/vlselect/main.go:169","msg":"remoteAddr: \"10.1.3.114:58522, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\"; requestURI: /select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999; the request couldn't be executed in 30.000 seconds; possible solutions: to increase -search.maxQueryDuration=30s; to pass bigger value to 'timeout' query arg"}
{"ts":"2024-09-06T11:09:12.526Z","level":"error","caller":"net/http/server.go:3416","msg":"http: response.Write on hijacked connection from github.com/klauspost/compress/gzhttp.(*GzipResponseWriter).startPlain (compress.go:292)"}
{"ts":"2024-09-06T11:09:53.571Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.056 seconds: remoteAddr=\"10.1.3.114:37574, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=consumer&from=1725562800000&query=%2A&to=1725649199999\""}
```
I have a big amount of logs (~200 million). Maybe the problem is related to this. But I have a loki-stack on another Kubernetes cluster with bigger amount of logs. And there is no such problem.

**Comment by dmitryk-dk** [comment]
> You are right. It is error 504 gateway timeout. I looked and there is no proxy between grafana and victorialogs. Also I looked at victorialogs logs:
> 
> ```
> {"ts":"2024-09-06T11:09:12.526Z","level":"warn","caller":"VictoriaMetrics/app/vlselect/main.go:169","msg":"remoteAddr: \"10.1.3.114:58522, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\"; requestURI: /select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999; the request couldn't be executed in 30.000 seconds; possible solutions: to increase -search.maxQueryDuration=30s; to pass bigger value to 'timeout' query arg"}
> {"ts":"2024-09-06T11:09:12.526Z","level":"error","caller":"net/http/server.go:3416","msg":"http: response.Write on hijacked connection from github.com/klauspost/compress/gzhttp.(*GzipResponseWriter).startPlain (compress.go:292)"}
> {"ts":"2024-09-06T11:09:53.571Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.056 seconds: remoteAddr=\"10.1.3.114:37574, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=consumer&from=1725562800000&query=%2A&to=1725649199999\""}
> ```
> 
> I have a big amount of logs (~200 million). Maybe the problem is related to this. But I have a loki-stack on another Kubernetes cluster with bigger amount of logs. And there is no such problem.

Yeah, I think the problem is with that. We need to discuss with our team about the problem

**Comment by dmitryk-dk** [comment]
> field_values

Could you try to increase the `-search.maxQueryDuration` to 60s before I will check this problem with our team?

**Comment by Neko-Follower** [comment]
Sure

**Comment by Neko-Follower** [comment]
I set `--search.maxQueryDuration=60` for victorialogs and timeout for datasource plugin, but it still canceled after 30s
![Снимок экрана 2024-09-06 в 17 12 36](https://github.com/user-attachments/assets/5fa9acfc-5b90-42f3-97a8-8f9db4fb73e6)
```
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:12","msg":"build version: victoria-logs-20240710-011043-tags-v0.28.0-victorialogs-0-gb173f24041"}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:13","msg":"command-line flags"}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.enable=\"true\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.prefix=\"VM_\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -loggerFormat=\"json\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -retentionPeriod=\"90d\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -search.maxQueryDuration=\"1m0s\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -storageDataPath=\"/storage\""}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/app/victoria-logs/main.go:42","msg":"starting VictoriaLogs at \"[:9428]\"..."}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/app/vlstorage/main.go:62","msg":"opening storage at -storageDataPath=/storage"}
{"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/memory/memory.go:42","msg":"limiting caches to 8326400409 bytes, leaving 5550933607 bytes to the OS according to -memory.allowedPercent=60"}
{"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/app/vlstorage/main.go:68","msg":"successfully opened storage in 7.489 seconds; smallParts: 1565; bigParts: 87; smallPartBlocks: 65427; bigPartBlocks: 45591; smallPartRows: 123419855; bigPartRows: 85053177; smallPartSize: 6588406481 bytes; bigPartSize: 4644403000 bytes"}
{"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/app/victoria-logs/main.go:50","msg":"started VictoriaLogs in 7.489 seconds; see https://docs.victoriametrics.com/victorialogs/"}
{"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:119","msg":"starting server at http://127.0.0.1:9428/"}
{"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:120","msg":"pprof handlers are exposed at http://127.0.0.1:9428/debug/pprof/"}
{"ts":"2024-09-06T12:03:03.380Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.063 seconds: remoteAddr=\"10.1.3.114:58062, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999\""}
{"ts":"2024-09-06T12:04:30.422Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.052 seconds: remoteAddr=\"10.1.3.114:59718, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999\""}
```

**Comment by dmitryk-dk** [comment]
> I set `--search.maxQueryDuration=60` for victorialogs and timeout for datasource plugin, but it still canceled after 30s ![Снимок экрана 2024-09-06 в 17 12 36](https://private-user-images.githubusercontent.com/83747975/365158363-5fa9acfc-5b90-42f3-97a8-8f9db4fb73e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjUwODMsIm5iZiI6MTcyNTYyNDc4MywicGF0aCI6Ii84Mzc0Nzk3NS8zNjUxNTgzNjMtNWZhOWFjZmMtNWI5MC00MmYzLTk3YTgtOGY5ZGI0ZmI3M2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyMTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDMyZDk1ZmMwMmY3MjE5ZDE2OTc1M2Q5ZTUxODViN2Q1ODk1YjJhMDM2ZWVhOTE0ZjhhNmE5ZGVjZTNhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Gdpzr2R0Z5JgGuuWTqddWQtqALUxMDaJtDnkGSvvkM)
> 
> ```
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:12","msg":"build version: victoria-logs-20240710-011043-tags-v0.28.0-victorialogs-0-gb173f24041"}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:13","msg":"command-line flags"}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.enable=\"true\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.prefix=\"VM_\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -loggerFormat=\"json\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -retentionPeriod=\"90d\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -search.maxQueryDuration=\"1m0s\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -storageDataPath=\"/storage\""}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/app/victoria-logs/main.go:42","msg":"starting VictoriaLogs at \"[:9428]\"..."}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/app/vlstorage/main.go:62","msg":"opening storage at -storageDataPath=/storage"}
> {"ts":"2024-09-06T12:02:06.352Z","level":"info","caller":"VictoriaMetrics/lib/memory/memory.go:42","msg":"limiting caches to 8326400409 bytes, leaving 5550933607 bytes to the OS according to -memory.allowedPercent=60"}
> {"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/app/vlstorage/main.go:68","msg":"successfully opened storage in 7.489 seconds; smallParts: 1565; bigParts: 87; smallPartBlocks: 65427; bigPartBlocks: 45591; smallPartRows: 123419855; bigPartRows: 85053177; smallPartSize: 6588406481 bytes; bigPartSize: 4644403000 bytes"}
> {"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/app/victoria-logs/main.go:50","msg":"started VictoriaLogs in 7.489 seconds; see https://docs.victoriametrics.com/victorialogs/"}
> {"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:119","msg":"starting server at http://127.0.0.1:9428/"}
> {"ts":"2024-09-06T12:02:13.841Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:120","msg":"pprof handlers are exposed at http://127.0.0.1:9428/debug/pprof/"}
> {"ts":"2024-09-06T12:03:03.380Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.063 seconds: remoteAddr=\"10.1.3.114:58062, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999\""}
> {"ts":"2024-09-06T12:04:30.422Z","level":"info","caller":"VictoriaMetrics/app/vlselect/main.go:161","msg":"client has canceled the request after 30.052 seconds: remoteAddr=\"10.1.3.114:59718, X-Forwarded-For: 10.53.221.31, 10.1.8.74, 10.1.8.74\", requestURI: \"/select/logsql/field_values?field=namespace&from=1725562800000&query=%2A&to=1725649199999\""}
> ```

Thank you for the provided information. I think i will be back on Monday with more information. Both your issues are related to this problem.

**Comment by Neko-Follower** [comment]
Thank you very much. I'll be waiting

**Comment by Neko-Follower** [comment]
Hi, I checked the new v0.5.0 release. Issue with Timeout gone. The values ​​are loaded instantly, i like it. 

But Issue with query filter is still relevant.
![Снимок экрана 2024-09-16 в 11 04 51](https://github.com/user-attachments/assets/6f083c4b-0dc9-4112-9fa8-0134761533ee)

Grafana v11.2.0
VictoriaLogs v0.28.0
VictoriaLogs datasource plugin v0.5.0

**Comment by dmitryk-dk** [comment]
> Hi, I checked the new v0.5.0 release. Issue with Timeout gone. The values ​​are loaded instantly, i like it.
> 
> But Issue with query filter is still relevant. ![Снимок экрана 2024-09-16 в 11 04 51](https://private-user-images.githubusercontent.com/83747975/367660234-6f083c4b-0dc9-4112-9fa8-0134761533ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzA5NzEsIm5iZiI6MTcyNjQ3MDY3MSwicGF0aCI6Ii84Mzc0Nzk3NS8zNjc2NjAyMzQtNmYwODNjNGItMGRjOS00MTEyLTlmYTgtMDEzNDc2MTUzM2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNzY3YjU5ZjY3NjUwN2ViZDY2YTRiY2ZkODJjMjY1ZTFiMGZhZDZiOWJmODI1NGZlOGE5OTI2M2YyN2U1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw4DMYSqyw-U6sUA0OYRBqg96RD0OpTlcjW5n7p8dMo)
> 
> Grafana v11.2.0 VictoriaLogs v0.28.0 VictoriaLogs datasource plugin v0.5.0

Hi! Could you please share the request from Grafana and the response? Could you please check the VictoriaLogs logs, maybe there are another error or warning present?

**Comment by Neko-Follower** [comment]
Sure. Here is request and response.
![Снимок экрана 2024-09-16 в 12 46 51](https://github.com/user-attachments/assets/460c6c63-9c5f-4eb9-aab3-cca08d8f2880)

![Снимок экрана 2024-09-16 в 12 47 22](https://github.com/user-attachments/assets/abc913fb-df65-4dd6-93da-19280f2773c4)

I checked the logs in the VictoriaLogs. Didn't see any errors or warnings

**Comment by Neko-Follower** [comment]
I tried several queries. This doesn't seem to work with certain values.
![Снимок экрана 2024-09-16 в 13 16 58](https://github.com/user-attachments/assets/fb31f804-eaef-4975-9ed1-3478b5f0a244)
![Снимок экрана 2024-09-16 в 13 18 15](https://github.com/user-attachments/assets/7eea4a97-a0dd-484c-a5bd-392580a345f6)


This one work fine
![Снимок экрана 2024-09-16 в 13 19 54](https://github.com/user-attachments/assets/a2389499-9766-40f0-834c-d4053b883d79)
![Снимок экрана 2024-09-16 в 13 20 12](https://github.com/user-attachments/assets/f1449cc8-97b6-47d7-8e31-e8acab47bab8)

**Comment by dmitryk-dk** [comment]
Hi @Neko-Follower! I have investigated the issue. As far as I can see, there is a problem with Victorialogs API. Datasource works well. We will discuss it, and I will be back soon.

**Comment by valyala** [comment]
The issue with returning unexpected field values has been fixed at VictoriaLogs server side in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0c0f013a60c812f46df1b8fa2863d1038e0e0208 . This commit will be included in the next release of VictoriaLogs.

**Comment by valyala** [comment]
FYI, the issue with unexpected field values should be fixed in [v0.32.1-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release.

**Comment by p5i** [comment]
Hi. I had the same issue with unexpected values, returned by 'uniq'. It is fixed now in the v0.32.1.
But there is the same issue with 'count_uniq'.

**Comment by dmitryk-dk** [comment]
> Hi. I had the same issue with unexpected values, returned by 'uniq'. It is fixed now in the v0.32.1. But there is the same issue with 'count_uniq'.

Could you please create an issue in the VictoriaMetrics repository? Because this issue is mostly related to VictoriaLogs API

**Comment by Neko-Follower** [comment]
Hi @dmitryk-dk ! I'll try it during the day and tell you about the results

**Comment by Neko-Follower** [comment]
Hi! I updated to v0.32.1-victorilogs. Tested it, works great. Issue can be closed :)
