### ISSUE TITLE
Calls to /field_values should have `limit` param

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/victorialogs-datasource#75]
Calls to the mentioned API from the plugin should always include `limit` param (see https://docs.victoriametrics.com/victorialogs/querying/#querying-field-values):
> The /select/logsql/field_values endpoint supports optional limit=N query arg, which allows limiting the number of returned values to N. The endpoint returns arbitrary subset of values if their number exceeds N, so limit=N cannot be used for pagination over big number of field values. When the limit is reached, hits are zeroed, since they cannot be calculated reliably.

The limit should protect browser from crashing and lead to better user experience. If API returned `len(items) == limit` it also means that limit was reached, and plugin should notify the user about this and discard the response completely.

**Comment by Loori-R** [comment]
The feature was added in the [v0.6.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.6.0).
