### ISSUE TITLE
passing query through grafana variable doesn't work anymore

### ISSUE THREAD

**Issue by jenneron** [VictoriaMetrics/victorialogs-datasource#77]
Our use case is to restrict table with some label, but also provide an option to append another query or search field from user input.

For example, we can match `_AUDIT_LOGINUID:* *`

<details>

<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/5bd4fb1e-0c9a-41da-9b35-f3a0c6e07ee8)

</details>

But we can't set $query to `*` and match `_AUDIT_LOGINUID:* $query`:

<details>

<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/686b638d-b256-4869-9680-d8718a6253e8)

</details>

I believe this is due to escape characters in resulting expression: `expr:"_AUDIT_LOGINUID:* \"*\""`

While this might be sufficient to provide a search field, it makes a wrong expression when the variable is empty: `expr:"_AUDIT_LOGINUID:* \"\""`

It works when downgrading the plugin to 0.3.0:

<details>

<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/03eabfaf-af47-45c5-a1e1-d5a8fea6d5a3)

</details>

The resulting query with 0.3.0: `expr:"_AUDIT_LOGINUID:* *"`

The resulting query with 0.3.0 and empty variable: `expr:"_AUDIT_LOGINUID:* "`

**Comment by skoppe** [comment]
> Our use case is to restrict table with some label, but also provide an option to append another query or search field from user input.

Same here. Couldn't get it to work, good its a known issue.

BTW, victorialogs and this datasource are amazing.

**Comment by hagen1778** [comment]
Variables are correctly substituted starting from [v0.6.0](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.6.0). Closing this issue as done. Feel free to re-open if problem still exists.

**Comment by hagen1778** [comment]
@Loori-R @dima-vm please do the follow-ups on related tickets when making a release similarly to how we recommend it here https://docs.victoriametrics.com/contributing:
> `waiting for release` label is assigned to issues that required code changes and those changes were merged to upstream, but not released yet. Once a release is made, maintainers go through all labeled issues, leave a comment about the new release, remove the label, and close the issue.
