### ISSUE TITLE
Grafana not support multi-tenant for Victorialogs

### ISSUE THREAD

**Issue by nulldoot2k** [VictoriaMetrics/victorialogs-datasource#85]
Hi, Team!
I am currently deploying Victorialogs based on single version with replicas=2

![image](https://github.com/user-attachments/assets/448949a0-4d89-40eb-8bfd-dc07f4bc182b)

Previously my vmauth defined the noauth route via 2 tenant=1:1000 and tenant=1:1001

> tenant=1:1000
![image](https://github.com/user-attachments/assets/6f1b1758-ecad-4661-a419-d245158a76bb)
> tenant=1:1000 2 
![image](https://github.com/user-attachments/assets/3076580a-58b6-424c-8f07-a8e9d7007486)

Basically I see everything is healthy.
But there is a problem as follows

As I see Victorialogs already supports multiple tenants with closed article: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3792
But checking shows that on Grafana it is not possible to add that, because the outgoing route does not support that yet
Look at the path: **http://vmauth:8247/select/vmui**
with Tenant: "1:1000"

I think we need change path from /select/vmui/ to /select/1:1000/vmui/
Like that

![image](https://github.com/user-attachments/assets/c341cff4-1adf-437c-bb2c-d89397415206)

Outside solution using vmauth for users - tenant
Is there any solution for using auth in prefix_path ?

Thanks a lot!!!

**Comment by dmitryk-dk** [comment]
Hi @nulldoot2k ! The issue you mentioned in the description was implemented for the VictoriaMetrics. If you want to get logs via tenant you should use headers as described in the [documentation](https://docs.victoriametrics.com/victorialogs/#multitenancy) 

By default the (AccountID=0, ProjectID=0) [tenant](https://docs.victoriametrics.com/victorialogs/#multitenancy) is queried. If you need querying other tenant, then specify it via AccountID and ProjectID http request headers. For example, the following query searches for log messages at (AccountID=12, ProjectID=34) tenant:

`curl http://localhost:9428/select/logsql/query -H 'AccountID: 12' -H 'ProjectID: 34' -d 'query=error'`

So my question is, do you need a selector where you can select the tenant from which you want to query data?

**Comment by nulldoot2k** [comment]
@dmitryk-dk Hi bro, I added Header on my grafana datasource

![image](https://github.com/user-attachments/assets/bfc8735c-4d45-46c9-9cc1-f2cb06792402)

But it's not work, because it's default tenant 0:0
Seem grafana datasource not reference -H 'AccountID: 1' -H 'ProjectID: 1000'

**Comment by nulldoot2k** [comment]
Thanks for the quick reply. @hagen1778  how long will it take to add this func?

**Comment by hagen1778** [comment]
Hey @dmitryk-dk could you please verify that headers are correctly forwarded by the datasource?

**Comment by dmitryk-dk** [comment]
> Hey @dmitryk-dk could you please verify that headers are correctly forwarded by the datasource?

Yeah, will check it soon! If we need some other logic for this feature, we will implement it :)

**Comment by nulldoot2k** [comment]
Forward: https://github.com/VictoriaMetrics/victorialogs-datasource/issues/158
That cool, when it gets soon update :) 
But i want ask, As an administrator, I think pointing to Grafana is not a good choice for Dev.
Add a solution combining vmauth + victorialogs for endpoint
url: http://victorialogs/tenant/?relabels="abc=xyz"

**Comment by dmitryk-dk** [comment]
> Forward: #158 That cool, when it gets soon update :) But i want ask, As an administrator, I think pointing to Grafana is not a good choice for Dev. Add a solution combining vmauth + victorialogs for endpoint HTTP:
> 
> * URL: [http://victorialogs/tenant/?relabels="abc=xyz](http://victorialogs/tenant/?relabels=%22abc=xyz)"
> * Allowed cookies: session from echo server
> 
> ![image](https://private-user-images.githubusercontent.com/83489434/397189103-40c1ba3c-9140-446f-a45b-7e9a5475d1f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDI2ODUsIm5iZiI6MTczNDYwMjM4NSwicGF0aCI6Ii84MzQ4OTQzNC8zOTcxODkxMDMtNDBjMWJhM2MtOTE0MC00NDZmLWE0NWItN2U5YTU0NzVkMWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA5NTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZmYzN2FlNTg3Yjk0MDI2MGE1MjAwMzFjYjhjMjhiMGJiODAyOTljYmE0MTVlZjc2YTc5NDcxMmIxZDg3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qU1NQ8Y5r-JNaotP5uwaqWtEQSdXS583KST509MKQNM)

We will add support for the headers soon. Maybe next week

**Comment by dmitryk-dk** [comment]
Hi @nulldoot2k ! We released the new version of the plugin where we implemented support of the custom headers. 
Can try to use this [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.13.2)?

**Comment by nulldoot2k** [comment]
> Hi @nulldoot2k ! We released the new version of the plugin where we implemented support of the custom headers. Can try to use this [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.13.2)?

Of course, i'll apply them in our pre-release.
Thank you very much <3

**Comment by alongwill** [comment]
If we have logs from multiple tenants in Victoria Logs, is it possible for the `AccountID` header value to be changed  dynamically via the Grafana UI? Or would we need to create a Grafana data source for each tenant?

**Comment by dmitryk-dk** [comment]
> If we have logs from multiple tenants in Victoria Logs, is it possible for the `AccountID` header value to be changed dynamically via the Grafana UI? Or would we need to create a Grafana data source for each tenant?

Hi! For dynamic changes, we have created this PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7484. It can help to make the select component with different AccountID and ProjectID.

Changing headers is not possible because they are defined in the data source config. So, at that moment, you need to create different datasources with different headers set.
