### ISSUE TITLE
Wrong sorting of numerical data in grafana vars

### ISSUE THREAD

**Issue by Heyzi** [VictoriaMetrics/victorialogs-datasource#97]
When making a query, I'm getting incorrect sorting of numerical data (Preview of values):

<img width="487" alt="image" src="https://github.com/user-attachments/assets/d1db6e2c-127a-4e9f-a306-82f88f1332d5">
<img width="487" alt="image" src="https://github.com/user-attachments/assets/45d698c0-8482-4aa7-921d-963e7256c35d">
<img width="487" alt="image" src="https://github.com/user-attachments/assets/2f98090e-f7e9-45d8-a39d-9f7ebb293a10">
<img width="487" alt="image" src="https://github.com/user-attachments/assets/ab2a7fad-a108-4b01-beea-cff2fb70043c">

Accordingly, the sorting on the dashboard page is also incorrect

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/victorialogs-datasource/pull/107 was merged and will be available in the next release.
